### ISSUE TITLE
Setup works only in localhost

### ISSUE THREAD

**Issue by prem911** [simplesteph/kafka-stack-docker-compose#18]
When I setup the broker and zookeeper in a remote machine, then any message produced throws this error. Same for single or multi broker/zk arrangement.

$ bin/kafka-console-producer.sh --broker-list server-url:9092,server-url:9093,server-url:9094 --topic test
>message1

ERROR Error when sending message to topic test with key: null, value: 5 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for test-1: 1511 ms has passed since batch creation plus linger time

Note: I have the entry for /etc/hosts for kafka1

**Comment by simplesteph** [comment]
Hi Prem,
Setting up Kafka is hard. This is only intended for local development, and works as intended. 
This setup won't work in the cloud without substantial investment on your end to understand the setting KAFKA_ADVERTISED_LISTENERS. For short, set it to your remote machine's ip (public if you go over the internet, private if not). 
Happy learning!

**Comment by prem911** [comment]
Thanks Stephane!
Realising now that Kafka in blogs and Kafka in practical is way different!
I have gone through the various ENV params for external deployment. However, those have not yielded much result. Well, I will kind my way out.

**Comment by simplesteph** [comment]
Hi @prem911 . I do have a course online dedicated to understanding how to deploy Kafka externally. After looking through it I'm sure you'll understand how to deploy Kafka correctly.
https://www.udemy.com/kafka-streams/?couponCode=GITHUB

Happy learning!
Stephane
