### ISSUE TITLE
kafka-connect-ui connectivity error

### ISSUE THREAD

**Issue by jonathanmv** [simplesteph/kafka-stack-docker-compose#36]
Hello simplesteph, thanks for creating these useful docker-compose files.

I just finished the kafka cluster setup course and I'm trying to use the `full-stack.yml` docker-compose file but I'm getting a `connectivity error` on the web page.

I found [this answer in the course Q&A](https://www.udemy.com/kafka-cluster-setup/learn/v4/questions/4161712) but removing `network_mode: host` is not an option anymore as the `full-stack.yml` file doesn't include it.

I also tried running the command below because the person said that it worked for him and even this doesn't work for me.

```
sudo docker run --rm -p 8003:8000 -e "CONNECT_URL=http://[different-options]:8083" landoop/kafka-connect-ui:0.9.4
```
Different options for the CONNECT_URL: public-ec2-ip, kafka-connect, my-public-dns

I also looked for answers to this issue in the Q&A section of the course and here in Github but I can't find anything related to the connectivity error.

Thanks again for taking the time to suggest a solution

**Comment by simplesteph** [comment]
@jonathanmv sorry this will be an issue related to https://github.com/Landoop/kafka-connect-ui 
I suggest dealing with the issue there

Hope you'll figure it out!

**Comment by g2giovanni** [comment]
@jonathanmv Hi, did you find a solution? I'm stuck with the same issue.

**Comment by jonathanmv** [comment]
Hey @g2giovanni, I ended up with [https://gist.github.com/jonathanmv/bdda140b96a718cbf90a143ae80f101b](this) docker compose file that sets up Schema Registry UI, Kafka Connect, and Kafka Connect UI. Please notice that the urls are fake and since I have my cluster on AWS I used their Private DNS which comes in the form of **ip-172-31-9-1.ec2.internal** but in the file I have changed to **kafka1.ec2.internal** 

I hope that gist helps. Please let me know. Thank you

**Comment by g2giovanni** [comment]
Thanks @jonathanmv. My docker-compose file was fine. I lost a lot of time but at the end the problem was I need to increase the docker RAM in settings at 6 GB.

**Comment by uluzox** [comment]
> Thanks @jonathanmv. My docker-compose file was fine. I lost a lot of time but at the end the problem was I need to increase the docker RAM in settings at 6 GB.

That was also my solution. I am running with Docker for Mac. 
Container `kafka-stack-docker-compose_kafka-connect_1` exited with Code 137. After searching for it, I found the solution at https://www.petefreitag.com/item/848.cfm

Increase the memory usable by docker.
