### ISSUE TITLE
Kafka is not coming up

### ISSUE THREAD

**Issue by touseefzaki** [simplesteph/kafka-stack-docker-compose#56]
Hi, I am using Docker Toolbox for windows and trying to bring Single Zookeeper and Single Broker up.
I used the following command from the source folder
'docker-compose -f zk-single-kafka-single.yml up
with which i can see the servers are up but when i go to source folder by opening another docker window and try to create a topic it says 'Kafka-Topics' is a bad command. Not sure why?

**My Folder structure** 
Here are my configuration files i am
![KafkaFail](https://user-images.githubusercontent.com/46226708/59867111-efe50d80-93aa-11e9-91d1-8926fa8a3cf5.PNG)
 using which you have provided in the Udemy course. From this location only i used this command 'C:\Program Files\Docker Toolbox\kafka-stack-docker-compose-master'. Please let me know what i am doing wrong.

**Comment by simplesteph** [comment]
Just add the `kafka-topics.bat` (you're on windows) to your path and use that

**Comment by touseefzaki** [comment]
> Just add the `kafka-topics.bat` (you're on windows) to your path and use that

Thanks Stephane for the response

I tried doing that also. The server comes up with this command 'docker-compose -f zk-single-kafka-single.yml up'

Now the problem is with create and other kafka commands... I have basically done the following after starting the server

1) Tried to create topic using 'kafka-topics.bat --zookeeper 192.168.99.100:2181 --create --topic test --partitions 3 --replication-factor 1' command 

2) Also tried using 'kafka-topics.bat --zookeeper 127.0.0.1:2181 --create --topic test --partitions 3 --replication-factor 1'

In both of these cases i get the same message command not found.  It looks strange to me
![KafkaFailedToStart](https://user-images.githubusercontent.com/46226708/59936975-e1f8c080-946e-11e9-91eb-8e1598c0a0ba.PNG)
